ithaka/pharos

- .changeset/seven-cherries-try.md
- .github/workflows/chromatic.yml
- .github/workflows/release.yml
- .github/workflows/verify.yml
- .yarnrc
- docs/development/conventions/creating-a-release.md
- package.json
- packages/pharos/src/components/sidenav/pharos-sidenav.test.ts
- yarn.lock
By default, `yarn` always fetches dependencies from the network first before checking the cache. As a result we have not seen the full benefits of caching dependencies in our Github Actions builds. We can use `--prefer-offline` to tell Yarn to use the cache and only make network requests for anything missing from it. We should also cache `node_modules` to ensure Yarn does not fetch packages. This in combination with running linting and tests in parallel results in a reduction of one minute in average job duration.
- Add `--prefer-offline` for yarn installs in our workflows
- Cache `node_modules`
- Cache Playwright …
> ci: instruct yarn to give cache priority and cache node_modules

- .changeset/spicy-cats-knock.md
- packages/pharos-site/src/components/statics/component-status/StatusTable.module.css
- packages/pharos-site/src/components/statics/component-status/StatusTable.tsx
The design for the table intended to show that the drop shadow used for the table header on the component status page should only be visible when it's stickied.
Using `IntersectionObserver`, combined with css `top: -1px`, we're able to detect whether the header is stickied or not. We then apply the style as intended.
> documentation: update component status table to show shadow only when 'stickied'

- .changeset/purple-beans-cross.md
- packages/pharos/src/components/sidenav/pharos-sidenav-menu.scss
The sidenav on the site was not showing the last component link for `Textarea` because the expanded menu's max-height of 50rem had been reached.
- Increase max-height of sidenav menu
> fix(pharos): increase max-height of sidenav menu

- .changeset/fair-steaks-tan.md
- package.json
- packages/pharos-site/src/pages/components/component-status/status.json
- packages/pharos-site/static/styles/global.scss
- packages/pharos/package.json
- packages/pharos/src/components/image-card/PharosImageCard.react.stories.mdx
- packages/pharos/src/components/image-card/pharos-image-card.scss
- packages/pharos/src/components/image-card/pharos-image-card.test.ts
- packages/pharos/src/components/image-card/pharos-image-card.ts
- packages/pharos/src/components/image-card/pharos-image-card.wc.stories.mdx
- packages/pharos/src/components/layout/pharos-layout.test.ts
- packages/pharos/src/components/layout/pharos-layout.ts
- packages/pharos/src/components/link/pharos-link.scss
- packages/pharos/src/components/link/pharos-link.ts
- packages/pharos/src/components/toast/PharosToast.react.stories.mdx
- packages/pharos/src/index.ts
- packages/pharos/src/utils/scss/_mixins.scss
- yarn.lock
Add image card component to be used for presenting a list of items or collections on the platform.
- Add card component with `error` and `subtle` states
- Add `action-menu` attribute to render an action button to act as the trigger for the menu
- Add `collection` variant to present collection in 4:3 aspect ratio
- Add `tag` prop to `pharos-layout` to specify the HTML tag to use for the inner grid
- Update `playwright`
> feat(pharos): add image card component

- lint-staged.config.js
fixes #43 
- Exclude `.changeset` directory from lint-staged
> fix: exclude changesets from lint-staged

- .changeset/angry-dragons-eat.md
- packages/pharos/src/components/image-card/pharos-image-card.scss
- packages/pharos/src/components/image-card/pharos-image-card.test.ts
- packages/pharos/src/components/image-card/pharos-image-card.ts
Image cards in the error state should render a link around the "Preview not available" container and show metadata on hover in combination with the subtle state.
- render link for error image cards and allow subtle state
> fix(pharos): render link for error image cards and allow subtle state

- netlify.toml
We want to be able to access the Storybooks deployed on Netlify from the Pharos site using the pharos.jstor.org domain.
- Add toml with redirect rules
> ci: redirect to Storybooks from site

- .changeset/good-fans-hope.md
- packages/pharos/src/components/image-card/pharos-image-card.scss
fixes #56 
- Set overflow for subtle image cards
> fix(pharos): set overflow for subtle image cards

- netlify.toml
Attempt to fix routing when URL does not contain trailing slash using redirect status codes.
- Use redirect status codes for paths without a trailing slash
For preview builds, the Storybooks will redirect to the production build URL pharos.jstor.org.
> fix: update redirect logic

- .storybook/main/main.js
Our composed Storybook doesn't work on pharos.jstor.org because the references Storybooks have the same domain.
- Update references Storybook to https://pharos-storybooks.netlify.app/ versions
> fix: point to separate netlify deployment for composition

- .changeset/pink-fishes-sparkle.md
- packages/pharos-site/src/components/statics/PageSection.tsx
- packages/pharos-site/static/guidelines/alert.docs.mdx
- packages/pharos-site/static/guidelines/breadcrumb.docs.mdx
- packages/pharos-site/static/guidelines/button.docs.mdx
- packages/pharos-site/static/guidelines/checkbox.docs.mdx
- packages/pharos-site/static/guidelines/combobox.docs.mdx
- packages/pharos-site/static/guidelines/dropdown-menu-nav.docs.mdx
- packages/pharos-site/static/guidelines/dropdown-menu.docs.mdx
- packages/pharos-site/static/guidelines/footer.docs.mdx
- packages/pharos-site/static/guidelines/header.docs.mdx
- packages/pharos-site/static/guidelines/heading.docs.mdx
- packages/pharos-site/static/guidelines/icon.docs.mdx
- packages/pharos-site/static/guidelines/input-group.docs.mdx
- packages/pharos-site/static/guidelines/link.docs.mdx
- packages/pharos-site/static/guidelines/loading-spinner.docs.mdx
- packages/pharos-site/static/guidelines/modal.docs.mdx
- packages/pharos-site/static/guidelines/pagination.docs.mdx
- packages/pharos-site/static/guidelines/progress-bar.docs.mdx
- packages/pharos-site/static/guidelines/radio.docs.mdx
- packages/pharos-site/static/guidelines/select.docs.mdx
- packages/pharos-site/static/guidelines/sidenav.docs.mdx
- packages/pharos-site/static/guidelines/tabs.docs.mdx
- packages/pharos-site/static/guidelines/template.mdx
- packages/pharos-site/static/guidelines/text-input.docs.mdx
- packages/pharos-site/static/guidelines/textarea.docs.mdx
- packages/pharos-site/static/guidelines/toast.docs.mdx
- packages/pharos-site/static/guidelines/tooltip.docs.mdx
- packages/pharos-site/static/guidelines/type-styles.docs.mdx
Add storybook links to component pages now that it is public.
- add `storyBookType` prop to `PageSection` component which takes in the element type for a specified component
- if 'storyBookType' is passed, pharos link is rendered to component specified url
- pass  in `storyBookType` into the component sections
> docs(pharos-site): add storybook links to public component sections

- .changeset/shy-lizards-lie.md
- packages/pharos-site/src/components/Sidenav.tsx
Removes the design tokens overview link from the site while adding the logo guidelines to the brand expressions section.
> feat(pharos-site): reactivate logo guidelines and deactivate design token overview

- .changeset/stupid-laws-roll.md
- packages/pharos/src/components/base/overlay-element.ts
- packages/pharos/src/components/layout/pharos-layout.ts
- packages/pharos/src/components/tooltip/pharos-tooltip.ts
Custom boundaries have been restricted to what `document.querySelector` is able to return. We should allow elements in a shadow DOM to also be boundaries (which is now possible with the `deepSelector` utility function).
- Enable setting elements in a shadow DOM as tooltip boundary
- Add `id` to layout's inner container
> feat(pharos): enable setting elements in a shadow DOM as tooltip boundary

- build-ignore.sh
As shown in Netlify's [examples](https://docs.netlify.com/configure-builds/common-configurations/ignore-builds/#ignore-examples) we should use their environment variables to check against the last built commit to avoid deployments for merge commits.
- Use [CACHED_COMMIT_REF and COMMIT_REF](https://docs.netlify.com/configure-builds/environment-variables/#git-metadata)
> ci: use last built commit for ignore

- .changeset/smart-years-impress.md
- packages/pharos-site/gatsby-config.js
- packages/pharos-site/package.json
- yarn.lock
Gatsby adds a trailing slash when you refresh a page or access a subpath via a URL. This leads to images not loading correctly (such as the logo used in the header doc). It also messes with analytics for the site as the same URL with or without the slash are counted as separate pages.
- Use the official Gatsby plugin [gatsby-plugin-remove-trailing-slashes](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-remove-trailing-slashes) to remove trailing slashes
> fix(pharos-site): remove trailing slashes from Gatsby paths

- .changeset/flat-tools-decide.md
- packages/pharos-cli/src/templates/unit-test-template.js
Importing `html` from `@open-wc/testing` is deprecated. It should be imported from `lit` instead.
- import html from lit
> fix(cli): import html from lit

- .changeset/breezy-singers-reply.md
- packages/pharos-site/src/components/Sidenav.tsx
- packages/pharos-site/src/components/footer.module.css
- packages/pharos-site/src/components/footer.tsx
We should have links to JSTOR on the Pharos site so that new visitors can go there to learn more about it.
- Add links to JSTOR in the footer and sidenav
> feat(pharos-site): add links to JSTOR from site

- .changeset/ninety-ravens-exercise.md
- packages/pharos/src/components/breadcrumb/pharos-breadcrumb-item.ts
- packages/pharos/src/components/tooltip/pharos-tooltip.ts
When the slotted content provided to a `pharos-tooltip` is anything other than text, the desired overflow wrapping logic (30+ characters) breaks.
Example:
```html
<pharos-tooltip>
<div>I am some text that happens to be longer than 30 characters.</div>
</pharos-tooltip>
```
It appears that during the [upgrade to Lit 2](https://github.com/ithaka/pharos/pull/19) we added check to only look for text nodes. This PR undoes that so we can look for nodes other than text in order to assess their lengths. Not 100% sure I understand the original context to know if this is the correct fix or not.
> fix(pharos): update tooltip and breadcrumb overflow logic when slotted content is non-HTML

- .changeset/rare-brooms-film.md
- packages/pharos/src/components/image-card/pharos-image-card.test.ts
- packages/pharos/src/components/image-card/pharos-image-card.ts
Resolves #101 
- Add slot for title to image cards that renders when `title` prop is not set
> feat(image-card): add slot for title

- .changeset/nervous-chefs-dance.md
- packages/pharos/src/components/image-card/pharos-image-card.scss
- packages/pharos/src/components/image-card/pharos-image-card.ts
This centers images smaller than the width horizontally within the image card
Before:
After:
Adds CSS to have auto left/right margins
> fix(image-card): horizontally center image within card

- .changeset/empty-bikes-divide.md
- packages/pharos/src/components/image-card/pharos-image-card.scss
https://user-images.githubusercontent.com/13315416/124319249-eff67700-db47-11eb-992c-1d78a1516b54.mov
Unsets the link `contain: layout` styling
> style(image-card): unset `contain` for link surrounding image

- .changeset/kind-drinks-fold.md
- packages/pharos/src/components/toast/pharos-toast.scss
- packages/pharos/src/components/toast/pharos-toast.wc.stories.mdx
On mobile our toasts expand beyond the viewport as their widths are static and design did not specify styles for the viewport.
- Set max-width on mobile to `90vw`
> style(toast): set max-width on mobile

- .changeset/curvy-lies-develop.md
- packages/pharos/src/components/image-card/pharos-image-card.scss
Fixes issue where cards were misaligned and not taking up the full width of the grid column when their contents are narrower than the column width.
Add `width: 100%` to make cards take up full width and center their contents
Before:
https://user-images.githubusercontent.com/13315416/124817457-d5514300-df37-11eb-9e40-db909dc7e22c.mov
After:
https://user-images.githubusercontent.com/13315416/124817581-fe71d380-df37-11eb-956d-5db86d8f6518.mov
> style(image-card): force 100% width for better alignment within the grid

- .github/workflows/release.yml
- docs/development/conventions/creating-a-release.md
resolves #149 
- Update release action to merge `main` into `develop` after publishing
> ci: update release workflow to merge main into develop

- lint-staged.config.js
- packages/pharos/package.json
- packages/pharos/src/components/alert/pharos-alert.ts
- yarn.lock
We want checks to be run as early as possible during development to minimize rework after opening a pull request.
- Add `ts-lit-plugin` for better IDE hinting support
- Run `lit-analyzer` during pre-commit
> fix: run lit-analyzer on pre-commit

- .changeset/twelve-bananas-beg.md
- packages/pharos/src/components/image-card/pharos-image-card.scss
Before:
Now: 
Add a min-width to the title.
Needed for PLATO-1741
> Image card: Fix long title overflow

- .changeset/red-students-rescue.md
- packages/pharos/src/components/image-card/pharos-image-card.scss
Promotional image cards are meant to allow for a broader range of possible images because they're hand-chosen. This means they should also be given room to be sized dynamically/bespoke.
Remove the stringent `14rem` height from promotional images. Images can be sized either with layouts or explicitly with CSS by the consumer.
> Image Card: Allow promotional variant images to have dynamic height

- .changeset/smart-peaches-compete.md
- packages/pharos/src/components/select/pharos-select.test.ts
- packages/pharos/src/components/select/pharos-select.ts
Fixes #168 
- set the selection when a value is initially passed
The `value` attribute is not a standard for native selects. [Frameworks such as React and Vue](https://reactjs.org/docs/forms.html#the-select-tag) use it to improve developer experience. Because our component has to render options instead of using a slot, `value` does not get reflected on initial render and so we have to manually set it.
> fix(select): set the selection when a value is initially passed

- .changeset/polite-tables-breathe.md
- packages/pharos/src/components/image-card/pharos-image-card.scss
We do not want promotional image card titles to be truncated as they serve marketing/promotion needs and so should be fully legible.
- Update styles to not apply truncation on the `promotional` variant
> fix(image-card): do not truncate promotional titles

- .changeset/chilled-birds-invite.md
- packages/pharos/src/utils/scss/_mixins.scss
Currently auto margins are applied at and between every breakpoint for the `1-col` preset. When going below the medium breakpoint, the margins apply undesired shrinking of elements such as inputs. We can remove these margins when going below `medium` as the layout's margins are static and not fluid like the ones above the breakpoint.
- Apply margins for `1-col` layouts only at `medium` and above
> fix(layout): apply margins for breakpoints medium and above for 1-col

- .changeset/wicked-waves-sparkle.md
- packages/pharos/src/components/combobox/pharos-combobox.test.ts
- packages/pharos/src/components/combobox/pharos-combobox.ts
Fixes #159 
- Clear the displayed value when the value is cleared programmatically
This only handles situations where an option has been first selected and then `value` is reset. To clear the display value with random text or when there is no matching option we would need to provide a public method consumers could call on the combobox instance.
> fix(combobox): clear input when value is reset

- .changeset/pretty-impalas-explain.md
- packages/pharos/src/components/combobox/pharos-combobox.test.ts
- packages/pharos/src/components/combobox/pharos-combobox.ts
#160 
* Add `tabindex="-1"` to the combobox button to avoid keyboard focus
* Update click and blur handling for desired behavior
This removes the ability to toggle the combobox open/closed by clicking the button repeatedly—we could change that, but this is consistent with the WAI ARIA example.
> fix(combobox): stop button from receiving focus

- .changeset/yellow-turtles-watch.md
- packages/pharos-site/src/components/Sidenav.tsx
- packages/pharos-site/src/pages/components/component-status/status.json
- packages/pharos-site/src/pages/components/toggle-button-group/index.mdx
- packages/pharos-site/static/guidelines/toggle-button-group.docs.mdx
Adds documentation for the `PharosToggleButtonGroup`
> docs(pharos-site): add toggle button group documentation

- .changeset/stale-baboons-happen.md
- packages/pharos/src/components/image-card/pharos-image-card.test.ts
- packages/pharos/src/components/image-card/pharos-image-card.ts
This allows the pharos consumer to add a label to the link surrounding the image on the image card
Creates new `image-link-label` property on the image card and adds the value as an `aria-label` to the markup if defined
Not sure if bugfix or feature. Thoughts on if this should be a minor change vs a patch?
> feat(image-card): add property for setting aria label on the image link

- .changeset/thick-chicken-sin.md
- packages/pharos/src/components/image-card/pharos-image-card.scss
Closes #197
This unsets the `contain: layout` style from the link element
Marked as potential browser bug because the misaligned tooltip predicating this issue is only present on Firefox.
> fix(image-card): remove containment styling for title

- .changeset/stupid-experts-pretend.md
- packages/pharos/src/components/breadcrumb/pharos-breadcrumb.scss
Fixes #195 
Allow the flex items to wrap when there isn't enough space on a single line using `flex-wrap: wrap`.
> fix(breadcrumb): allow items to wrap

- .changeset/late-dots-kick.md
- packages/pharos/src/components/input-group/PharosInputGroup.react.stories.mdx
- packages/pharos/src/components/input-group/pharos-input-group.ts
- packages/pharos/src/components/input-group/pharos-input-group.wc.stories.mdx
- packages/pharos/src/components/text-input/pharos-text-input.ts
Fixes #204 
* Consider the width of the appended input group content (like buttons) when determining the icon's placement and the input's padding.
* Add a story to show validity for input groups to identify regressions
I replaced instances of `super['_input']` with `this._input` and made `_input` a protected instead of private member of the base class. This feels fine encapsulation-wise and makes the inheritance feel more smooth.
> fix(input-group): shift validity icon placement

- .changeset/nine-shoes-joke.md
- packages/pharos/src/components/button/PharosButton.react.stories.mdx
- packages/pharos/src/components/button/pharos-button.scss
- packages/pharos/src/components/button/pharos-button.test.ts
- packages/pharos/src/components/button/pharos-button.ts
- packages/pharos/src/components/button/pharos-button.wc.stories.mdx
This PR introduces a new button variant that is intended to be placed "overlayed" on top of some other content. It is a variant that provides a dark background (with slight opacity) and a white font.
What is looks like:
Added a variant called `overlay` and the css style to accomplish it. Very open to feedback on the variant name of `overlay`. Struggled to land on something better.
> feat(button): Add overlay variant

- .changeset/many-toys-hope.md
- packages/pharos-site/static/guidelines/image-card.docs.mdx
Fixes #161 
Add explicit widths to examples, using a wider width for the collection variant to give a sense of its usage in the wild.
> Docs: Update image card examples to a reasonable width

- .changeset/two-pandas-rule.md
- packages/pharos-site/src/components/footer.module.css
- packages/pharos-site/src/components/footer.tsx
- packages/pharos-site/src/pages/brand-expressions/logos.mdx
Fix regressions from #221 
- Move `grid-area` to footer container
- Fix giant logo
> fix(site): correct footer on smaller breakpoints

- .changeset/silent-worms-bake.md
- packages/pharos/package.json
To register multiple components, we should allow folks to import from the entry point and [guarantee tree shaking](https://webpack.js.org/guides/tree-shaking/#clarifying-tree-shaking-and-sideeffects) from Webpack:
```
import { PharosLink, PharosButton, PharosIcon } from "@ithaka/pharos";
```
- Specify side effects in `package.json`
```
import { PharosButton } from "@ithaka/pharos";
```
**Before:**
**After:**
> perf(pharos): specify package side effects

- .changeset/lovely-mangos-cheer.md
- packages/pharos/package.json
By default, Webpack uses an index as the id of dynamically imported chunks. This is why our icons show up as numerically named exports. We can use Webpack [magic comments](https://webpack.js.org/api/module-methods/#magic-comments) to use the resource's name instead.
- Place magic comment `/* webpackChunkName: '[request]' */` within dynamic imports
I solemnly swear that I am up to no good
> fix: use request name for dynamic import chunks

- README.md
People like to know how big NPM packages currently are, and how they've changed in size over time. Bundlephobia is a good source of this information, automatically maintaining this record for packages published publicly to NPM.
Add a Bundlephobia shield near the top of the README next to the other shields. The shield image links to the Bundlephobia page for the package.
I put all the linked shields on a single line each to remove hyperlinked whitespace.
> docs: add bundlephobia shield to README

- .github/CODEOWNERS
We want to minimize manual work, including assigning reviewers for code changes. Especially right now, all changes are always reviewed by the same group (@ithaka/pharos-maintainers).
Add a [CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) file that points all changes to the Pharos maintainers.
We may choose to automatically choose a subset of reviewers from the Pharos maintainers team using [automatic assignment](https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-rev …
> chore: add codeowners file for auto PR assignment

- .changeset/happy-seas-fix.md
- packages/pharos-site/src/pages/getting-started.mdx
- packages/pharos/README.md
- packages/pharos/src/components/link/pharos-link.scss
- packages/pharos/src/components/link/pharos-link.ts
- packages/pharos/src/utils/scss/_mixins.scss
When testing the latest release in a Vue 3 app, all links with a `href` attribute were rendering as buttons. This is likely because attribute checks do not cause a re-render and a timing issue with Vue's lifecycle handling. So instead we can check if the component's `href` property is undefined to determine if it contains the `href` attribute or not.
- Check `href` prop for render
Noticed the link buttons also had a different letter-spacing so updated the `link-base` mixin
> fix(link): check href prop for render

- .changeset/thick-rabbits-happen.md
- .github/workflows/size-limit.yml
- package.json
- packages/pharos/package.json
- yarn.lock
To make package size improvements (and avoid degradations) we should have a consistent method to measure it and display this information on pull requests.
- Add [size-limit](https://github.com/ai/size-limit) package and `preset-small-lib` to measure package size via `esbuild`
- Add [GitHub action](https://github.com/andresz1/size-limit-action) that compares package size against `develop`
The action correctly calculates the package size of this branch but fails because when checking out `develop` notices `size-limit` dependencies are missing. This will be fixed once merged. Can open a test PR …
> ci: add size-limit action

- .storybook/webpack.config.js
- package.json
- packages/pharos/tsconfig.json
- yarn.lock
Resolves #287 
As of TypeScript 4.3.1+, [one must specify `useDefineForClassFields: false` explicitly](https://github.com/evanw/esbuild/issues/1354#issuecomment-855452057) when targeting ESNext, because [TC39 now uses the same syntax](https://www.typescriptlang.org/tsconfig#useDefineForClassFields) and these would conflict otherwise.
Updating this configuration allows the Storybook configuration to continue working. 
Pharos itself never broke because it is currently targeting `es2019`. Chromatic didn't catch this because it targets `firefox65` because Chromatic has a really crusty old Firefox. …
> fix(storybook): add useDefineForClassFields false

- .changeset/cuddly-rabbits-attack.md
- packages/pharos/src/components/dropdown-menu/pharos-dropdown-menu-item.test.ts
- packages/pharos/src/components/dropdown-menu/pharos-dropdown-menu-item.ts
Fixes #279
Whenever we assign `rel` attribute to DropdownMenuItem, attribute value will be passed to underlying anchor tag
> fix(dropdown-menu-item): pass rel attribute from menu item to anchor tag

- .changeset/cuddly-owls-type.md
- packages/pharos-site/static/styles/global.scss
- packages/pharos/src/components/header/PharosHeader.react.stories.mdx
- packages/pharos/src/components/header/pharos-header.scss
- packages/pharos/src/components/header/pharos-header.ts
- packages/pharos/src/components/header/pharos-header.wc.stories.mdx
- packages/pharos/src/pages/shared/react/Header.tsx
- packages/pharos/src/pages/shared/wc/header.ts
The latest branded designs for the header need a more sophisticated change to the gridding at different breakpoints. Namely, the header should be a 3-column/2-row grid on large screens, but a 3-column/3-row grid on smaller screens.
Update the CSS grid layout to add these new grid areas and corresponding slots to fill the content. The change keeps these areas named rather agnostically, for now, but we can consider whether the areas become more opinionated about the content that goes there if we only ever use it this one way, or we see that multiple usages keep the same pattern.
Removed the …
> feat(header): update slots and grid for new designs

- .changeset/wicked-actors-burn.md
- packages/pharos/src/components/header/pharos-header.scss
The changes made in #295 kept the content centered within its respective grid row—however, we must ensure the content in the new top and bottom areas presses up against the top and bottom borders respectively to avoid gaps due to implicit space calculations during CSS grid layout.
Change `align-self` from `center` to the appropriate `start`/`end` for each area.
> fix(header): push navigation areas to boundaries

- .changeset/quick-fireants-cheer.md
- packages/pharos/src/components/toast/pharos-toast.scss
- packages/pharos/src/components/toast/pharos-toast.test.ts
- packages/pharos/src/components/toast/pharos-toast.ts
- packages/pharos/src/components/toast/pharos-toast.wc.stories.mdx
Resolves #318
Add an info variation to toast. This will be used for showing the progress to users when we are working on their requests.
Add "info" as a valid status for toast and use the exclamation icon with feedback info color.
> Feat(toast): add info variation

- .changeset/new-cameras-prove.md
- .github/workflows/size-limit.yml
- package.json
- packages/pharos/package.json
Fixes #337 (maybe)
The size limit action checks if Yarn is available and uses it if so. I see it's using npm when it runs, though, so Yarn is not available. Installing it prior to the action running might make things happier.
> fix: use yarn in size limit action

- packages/pharos/src/components/dropdown-menu/pharos-dropdown-menu.wc.stories.mdx
- packages/pharos/src/components/toast/pharos-toast.wc.stories.mdx
- packages/pharos/src/components/tooltip/pharos-tooltip.wc.stories.mdx
The stories changed here have delays built into them using `setTimeout`, but they `delay` value for Chromatic was either unset or set to the same value as the timeout. This results regularly in snapshots where the component state has not yet reached the desired one for testing, leading to noisy snapshot diffs on each pull request.
Updating the `delay` value to be longer than the `setTimeout` values should result in a more stable testing experience.
> fix(chromatic): update delays for visual snapshot tests

- .changeset/pink-needles-jump.md
- packages/pharos/src/components/image-card/pharos-image-card.scss
- packages/pharos/src/components/image-card/pharos-image-card.test.ts
- packages/pharos/src/components/image-card/pharos-image-card.ts
- packages/pharos/src/components/image-card/pharos-image-card.wc.stories.mdx
- yarn.lock
This PR adds three new features to the image card:
1. New `selectable` and `collection-selectable` image card variants. There is also a `subtle-select` prop that more discretely shows the card's selectability.
2. New image card 'disables' states
3. New styling for the error state
All three of these (and some of their combinations) are visible here:
- Added new selectable variants to image card
- Added props for disabled and sublte-select
- Used variants and props to render checkbox
- Added onMouseEnter/Exit listeners to handle those events
- Use events, props, and classMap to use relevant classes for each variant's …
> ImageCard: Selectable and disabled variants, new styling for error variant

- build-ignore.sh
The Pharos Storybooks haven't been built since 2022-03-31.
In #370 we determined that the $CACHED_COMMIT_REF is sometimes the same as the $COMMIT_REF. In the absence of other understanding of why that would be, we can ensure we run the build when these two values are the same.
> fix(build): always build if the compared commits are the same

- .changeset/small-beers-double.md
- packages/pharos/src/components/image-card/pharos-image-card.ts
I released the selectable and disabled image cards recently, but the styling for the selectable card variant in a disabled state is not showing as desired. Currently it lacks the background color of a selectable card. This change fixes that issue. 
Updated the criteria to use the selectable css class.
> ImageCard: Use gray background on selectable disabled card

- .changeset/beige-oranges-walk.md
- packages/pharos/src/components/image-card/pharos-image-card.scss
- packages/pharos/src/components/image-card/pharos-image-card.test.ts
- packages/pharos/src/components/image-card/pharos-image-card.ts
#377 
Moves the checkbox within the rest of the card element where it is visually contained
Remove mouse listener events on checkbox
This also looks to remove re-render on mouse move when hovering the checkbox. If mouse is moving a lot that could add up to hundreds to thousands of re-renders in a short period of time. 
https://user-images.githubusercontent.com/13315416/181800423-a9c49d9b-685b-483a-94ab-358c96391e37.mov
> fix(card): restructure cards to avoid extra mouse events preventing selection in Safari

- .github/PULL_REQUEST_TEMPLATE.md
- packages/pharos-site/src/components/statics/component-status/StatusTable.tsx
- packages/pharos-site/src/pages/components/component-status/status.json
We would like a quick reference to understand when a component was last changed.
- Remove obviated Callout row
- Add last updated versions to status.json
- Link version text to relevant changelog heading (this may not work for
all versions as some changelog entries are in a legacy file)
This will not be ideal to update, at the moment, but gives us a starting place. The main challenge being that, at the time that a change is merged, the release version number is not necessarily known. Multiple changes may be included in a release, and even though one change may be a patch another change may be a …
> feat(site): add last updated column to status page

- .changeset/spicy-geckos-worry.md
- packages/pharos/src/components/image-card/pharos-image-card.scss
- packages/pharos/src/components/image-card/pharos-image-card.test.ts
- packages/pharos/src/components/image-card/pharos-image-card.ts
This PR adds keyboard accessibility to the selectable pharos image card variants.
Tab 1 => focus to card 
Tab 2 => focus to checkbox
Spacebar => select checkbox 
New function to handle keyboard events. Use various details from the keyboard event to determine if we should show the checkbox.
> ImageCard: Selectable Image card keyboard accessibility 

- .changeset/light-cups-guess.md
- packages/pharos/src/components/image-card/pharos-image-card.ts
Allows the click event on image cards to propagate in order to close modals on the same page.
Removed event.stopPropagation from _cardToggleSelect, and added a check in order to prevent the main body of the function from being executed twice.
> ImageCard: remove event.stopPropagation from _cardToggleSelect

- .changeset/tender-ways-impress.md
- packages/pharos/src/utils/scss/_mixins.scss
Safari in particular puts margin on some form control elements, and we hadn't addressed the default vertical margin for text inputs, meaning the inputs could (and do) look different depending on the user agent.
This change explicitly sets that margin to 0, allowing all browsers to be consistent.
> TextInput: explicitly set margin to avoid undesired user agent styles

- .changeset/stupid-ravens-rest.md
- packages/pharos/src/components/checkbox/pharos-checkbox.ts
- packages/pharos/src/components/radio-button/pharos-radio-button.ts
Only native `<a>` tags and unscoped `<pharos-link>` tags were clickable in these form controls; scoped tags were not.
Include scoped Pharos Link elements in the link selector.
> Checkbox, RadioButton: allow for scoped pharos links

- .changeset/bright-socks-fold.md
- packages/pharos/src/components/toast/pharos-toast.test.ts
- packages/pharos/src/components/toast/pharos-toast.ts
- packages/pharos/src/components/toast/pharos-toast.wc.stories.mdx
- packages/pharos/src/components/toast/pharos-toaster.test.ts
- packages/pharos/src/components/toast/pharos-toaster.ts
[PLATO-2561](https://jira.jstor.org/browse/PLATO-2561)
This PR addresses this pharos issue: #378
- Added new events for toast updates and programatic dismissal.
- Provide option for toast to stay open indefinitely.
- Added id prop so if there are multiple toasts, the consuming app can maintain them independently.
> Toast: Make updateable

- .changeset/nasty-rockets-confess.md
- .eslintrc.js
- packages/pharos/src/components/link/PharosLink.react.stories.mdx
- packages/pharos/src/components/link/pharos-link.scss
- packages/pharos/src/components/link/pharos-link.ts
- packages/pharos/src/components/link/pharos-link.wc.stories.mdx
- packages/pharos/src/utils/scss/_mixins.scss
We want the visited links styling to show up for Pharos links, when the user has visited the link. The consumer of the component should be able to either apply the visited links styling or not apply by specifying the `visitable` property on the Pharos Link component, which is defaulted to `false`
We add css rule to apply the required styling for the pharos link instance that has `visitable` property specified as `true`,
> Link: Allow for visited links styling

- .changeset/angry-guests-occur.md
- package.json
- packages/pharos/src/components/heading/pharos-heading.scss
- packages/pharos/src/components/link/PharosLink.react.stories.mdx
- packages/pharos/src/components/link/pharos-link.wc.stories.mdx
Headings were not properly reflecting color when linked inside a visited link, added in #409.
Remove `color: inherit` which was added when headings were first introduced. We may have removed `inherit` from other properties along the way for similar reasons.
> Heading: Fix text color inheritance for linked headings

- .changeset/blue-toys-relate.md
- .changeset/bright-clouds-bake.md
- packages/pharos/src/components/image-card/PharosImageCard.react.stories.mdx
- packages/pharos/src/components/image-card/pharos-image-card.test.ts
- packages/pharos/src/components/image-card/pharos-image-card.ts
- packages/pharos/src/components/image-card/pharos-image-card.wc.stories.mdx
- packages/pharos/src/components/link/pharos-link.scss
For a link with `indicate-visited` set to `true`, when being visited, if the link contains underline on hover, then the underline color should be consistent with text color i.e `--pharos-color-hover-primary`.
We add the `text-decoration-color` for the hover state for a visited link.
> Link & Image Card: Fix visited link hover state underline color for link + adding visited link support for title link in image card

- .changeset/selfish-actors-exist.md
- packages/pharos/src/components/image-card/pharos-image-card.ts
Currently, when the image card is in select mode, on a user click the card dispatches both a `click` and `pharos-image-card-selected`
Only emit the `pharos-image-card-selected` event such that we can have greater fidelity for the consumer.
> ImageCard: stopPropagation when toggling select

- .changeset/long-seahorses-obey.md
- packages/pharos/src/components/button/pharos-button.test.ts
- packages/pharos/src/components/button/pharos-button.ts
- packages/pharos/src/components/sidenav/pharos-sidenav-button.ts
- packages/pharos/src/components/toast/pharos-toast-button.ts
- packages/pharos/src/components/toggle-button-group/pharos-toggle-button-group.test.ts
- packages/pharos/src/components/toggle-button-group/pharos-toggle-button-group.ts
- packages/pharos/src/components/toggle-button-group/pharos-toggle-button.ts
Resolves #430 
Because the accessibility object model (AOM) is still in active development and doesn't enjoy wide browser vendor adoption at present, we need to maintain the accessibility for assistive technologies in the underlying native elements rather than the custom element host containers.
For things like buttons, this often means adding a property that gets rendered onto the underlying native element as an `aria-` attribute. Here, I add a `pressed` property to Button so that the ToggleButton can set it appropriately, which gets rendered as `aria-pressed` on the underlying `<button>` element. I also add a …
> ToggleButton: indicate toggle button state on underlying button elements

- .changeset/six-days-ring.md
- packages/pharos/src/components/tabs/pharos-tab.ts
Resolves #220 
Move firing of event from click handler to `updated` handler
> Tabs: fire event when tab selected programmatically

- .changeset/violet-tigers-perform.md
- packages/pharos/src/components/tabs/pharos-tab.test.ts
- packages/pharos/src/components/tabs/pharos-tab.ts
- packages/pharos/src/components/tabs/pharos-tabs.test.ts
- packages/pharos/src/components/tabs/pharos-tabs.ts
Fixes #346 
Supersedes #448
The design flaw in tabs was letting each individual tab manage its own state when clicked. This created issues with state management centralization and reasoning. This change instead moves the job of state management to the Tabs component, which coordinates the individual Tab and TabPanel components it contains. This results in smoother management and, ultimately, a more correct implementation.
> Tabs: fix initial tab selection in more cases

- .changeset/olive-days-melt.md
- packages/pharos/src/components/dropdown-menu/pharos-dropdown-menu.ts
In #434 I used the DropdownMenu host container to compute and apply position styles, rather than the visible `_menu` element.
Use `this._menu` for computing and applying styles, similar to how it's done in Tooltip.
> Dropdown: apply position computation and styles to proper element

- .svglintrc.js
- package.json
- yarn.lock
Resolves #343 
Use the `svglint` package to retrieve structured SVG content, and write a custom linting function for each of the common issues we've experienced:
* Icons keep the `<svg>` when they shouldn't, and get double-wrapped in `<svg>` when they render
* Icons keep `fill` attributes when they shouldn't, and consumers can't color those parts of the icon
Examples of testing out the linting rules:
> Infra: add icon SVG linting using svglint

- .changeset/stupid-crabs-remember.md
- packages/pharos/src/components/alert/pharos-alert.ts
- packages/pharos/src/components/breadcrumb/pharos-breadcrumb.ts
- packages/pharos/src/components/checkbox-group/pharos-checkbox-group.ts
- packages/pharos/src/components/combobox/pharos-combobox.ts
- packages/pharos/src/components/dropdown-menu-nav/pharos-dropdown-menu-nav.ts
- packages/pharos/src/components/dropdown-menu/pharos-dropdown-menu.ts
- packages/pharos/src/components/radio-group/pharos-radio-group.ts
- packages/pharos/src/components/sidenav/pharos-sidenav-menu.ts
- packages/pharos/src/components/tabs/pharos-tabs.ts
- packages/pharos/src/components/toggle-button-group/pharos-toggle-button-group.ts
- packages/pharos/src/utils/math.test.ts
- packages/pharos/src/utils/math.ts
Resolves #294 
- Replace imperative `querySelectorAll` (and some `querySelector`) with declarative `@queryAssignedElements` to move it out of the main component logic flow
- Replace forward/backward focus looping logic with a (custom) modulus calculation
I tried finding opportunities to use some of the other directives mentioned, but after trying a few it felt like the new code wasn't any clearer. We're mostly using ternaries rather than if/else in our rendering, so the `when`/`choose` resulted in longer code that was more cluttered.
> Refactor: use queryAssignedElements and simplify focus loops

- .changeset/blue-adults-attend.md
- .storybook/main/preview.js
- .storybook/react/preview.js
- .storybook/wc/preview.js
- packages/pharos-site/static/guidelines/tabs.docs.mdx
- packages/pharos/src/components/tabs/PharosTabs.react.stories.jsx
- packages/pharos/src/components/tabs/pharos-tab.scss
- packages/pharos/src/components/tabs/pharos-tab.ts
- packages/pharos/src/components/tabs/pharos-tabs.scss
- packages/pharos/src/components/tabs/pharos-tabs.ts
- packages/pharos/src/components/tabs/pharos-tabs.wc.stories.jsx
- packages/pharos/src/utils/math.ts
Resolves #292 
When a list of tabs is cramped horizontally, make them scrollable with indicators of scrollability.
> Tabs: make tabs scroll horizontally when cramped

- .storybook/main/preview.js
- .storybook/react/preview.js
- .storybook/wc/preview.js
The default "dark" background in `@storybook/addon-backgrounds` is a dark grey, and is almost identical in color to some of our components' background colors because they're meant to display on a black background.
- Add a `backgrounds` section to the `parameters` to set a hard white and black.
- Reduce code duplication and let both the web component and React Storybooks use the same `main` config.
- I tried using the `--pharos-color-white` and `--pharos-color-black` tokens in the config, and that mostly worked, but didn't properly show the color swatch next to the color option in the backgrounds …
> Storybook: use Pharos standard colors for background options

- .changeset/itchy-actors-worry.md
- package.json
- packages/pharos/package.json
- packages/pharos/src/components/toast/pharos-toast.test.ts
- packages/pharos/src/components/toast/pharos-toast.ts
- packages/pharos/src/components/toast/pharos-toaster.test.ts
- packages/pharos/src/components/toast/pharos-toaster.ts
- yarn.lock
When consumer doesn't provide an id to the toast, we used to set default toast id to be "toast", which cause duplicate id if same toast is emitted more than once. And because of the duplicated id, some toasts are not actually destroyed after they self-closed. Resulting in "ghost toasts" on the page. 
Make the id unique, no more ghost toasts.
> Toast: make toast IDs unique

- .changeset/empty-queens-listen.md
- packages/pharos/src/components/combobox/pharos-combobox.test.ts
- packages/pharos/src/components/combobox/pharos-combobox.ts
- packages/pharos/src/components/combobox/pharos-combobox.wc.stories.jsx
- packages/pharos/src/components/combobox/storyArgs.ts
Provides the option to loosely match user input values to the text options. By default there's an exact match and this excludes cases when a query or text has accents or different casing.
Added method to normalize strings using https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize#parameters
Users couldn't find their institutions when searching on https://www.jstor.org/site/collection-list/ because the official spelling contains an accent.
> Combobox: add loose-match option for matching query

- .changeset/perfect-cycles-drum.md
- packages/pharos/src/components/tabs/pharos-tab.ts
- packages/pharos/src/components/tabs/pharos-tabs.test.ts
- packages/pharos/src/components/tabs/pharos-tabs.ts
- packages/pharos/src/components/tabs/pharos-tabs.wc.stories.jsx
Fixes #462
A new attribute of pharos-tabs will manage the `selected-tab`, which refers to the index of the selected tab in the tablist.
On initial render, the `selected-tab` attribute of `pharos-tabs` will be used (which defaults to 0) to set the correct `pharos-tab` as `selected`
After updates, `selected-tab` prop on `pharos-tabs` should be used to programmatically update the selected tab. When a `pharos-tab` is clicked it dispatches an event and lets the parent manage its state. When a `pharos-tab` is clicked and it is already `selected` it does not dispatch an event to the parent.
> Tabs: move selected state management to pharos-tabs

- .changeset/cold-jeans-fail.md
- packages/pharos/src/components/toast/PharosToast.react.stories.jsx
- packages/pharos/src/components/toast/pharos-toast.test.ts
- packages/pharos/src/components/toast/pharos-toast.ts
- packages/pharos/src/components/toast/pharos-toast.wc.stories.jsx
- packages/pharos/src/components/toast/pharos-toaster.scss
- packages/pharos/src/components/toast/pharos-toaster.test.ts
- packages/pharos/src/components/toast/pharos-toaster.ts
Fixes #474 
Updates `PharosToaster` to use `ScopedRegistryMixin` and replace (most of) the DOM manipulation it was doing with declarative HTML rendering.
This is a breaking change because it changes the `detail` value for the `pharos-toast-close` event. Because this event was externally visible, this is technically an API change. I don't, however, believe any internal consumers were listening for this event. Because we're gearing up for v13 and this isn't otherwise too pressing, let's just wait and include it there.
> Toast: Update Toaster to use internally consistent scoping

- .changeset/silent-candles-smash.md
- packages/pharos/src/components/image-card/pharos-image-card.scss
- packages/pharos/src/components/image-card/pharos-image-card.ts
Fix the issue of no way to select checkbox in subtle selectable image card. We want to make the subtle select image card selectable through tabbing.
before: 
https://user-images.githubusercontent.com/38861633/215830430-df08f4cd-68d7-4a00-a889-880d58775e3d.mp4
after:
https://user-images.githubusercontent.com/38861633/215830721-bc55c9f8-2355-4d40-880c-d6319f3db203.mp4
Allow metadata layout show up via tab. Previously the metadata layout only shows up when you hover on it. Add "focus-within" to allow the layout show up when user tabs into the image card. So that the checkbox can also appear to be selected.
Focus on …
> ImageCard: allow tab into subtle image card checkbox

- .adr-dir
- docs/architecture/decisions/0001-record-architecture-decisions.md
- docs/architecture/decisions/0002-capture-design-decisions-in-a-token-hierarchy.md
- docs/architecture/decisions/0003-build-components-using-web-component-technology.md
- docs/architecture/decisions/0004-provide-a-react-wrapper-for-web-components.md
- docs/architecture/decisions/0005-use-visual-testing-in-addition-to-functional-testing.md
- docs/architecture/decisions/0006-use-css-custom-properties-for-component-styles.md
- docs/architecture/decisions/0007-use-scoped-elements-for-decoupled-teams.md
- docs/architecture/decisions/0008-evolve-tokens-in-backward-compatible-manner.md
- docs/architecture/decisions/README.md
- docs/architecture/decisions/index.md
I had wanted to capture a new architectural/process decision we were discussing today, and then found myself also wanting to capture some past pivotal decisions as well. I've been using architectural decision records (ADRs) in other contexts for a bit now and have been seeing returns on that, so thought we might give that a go here.
The important new decision revolves around managing token changes in a distributed team setting and how to avoid issues such as broken styling due to unexpectedly missing tokens. 
This change uses [adr-tools](https://github.com/npryce/adr-tools) to create several ADRs and link them …
> Backfill architecture decision records

- .changeset/metal-tomatoes-heal.md
- packages/pharos/src/components/footer/pharos-footer.styles.scss
Google Translate seems to have changed their DOM recently and removed a class we use for styling purposes.
Remove the now-missing class from the selector.
This could theoretically open up our styles to other links that are present, but because the widget isn't complex and the only other precision we could give is DOM ordering which feels more fragile, it feels best to go this route for now.
> Footer: update DOM selectors for Google Translate widget

- .changeset/plenty-dots-remember.md
- packages/pharos/src/components/link/pharos-link.ts
Adds extra information for users to use the `flex` attribute when using a nested heading so that it's visually accessible in all browsers.
> Docs: Update flex attribute docs for links 

- .changeset/warm-cobras-knock.md
- packages/pharos-site/static/guidelines/link.docs.mdx
#button
Links without an `href` attribute render as a button, and the canonical example Link in the docs did not have an `href`, so rendering as a button may serve to confuse newcomers.
Add `href="#"` in line with other examples on the page.
Fixes #507 
Closes #508
> fix(site): add missing href to example Link

- .changeset/grumpy-emus-impress.md
- packages/pharos/scripts/build-react.js
- packages/pharos/src/components/button/pharos-button.ts
- packages/pharos/src/components/button/storyArgs.ts
Fixes #511 
Use `undefined` instead of `'undefined'` as the default value. This causes `ifDefined` not to render the `aria-pressed` attribute unless given an explicit value.
> Button: Only render aria-pressed when explicitly defined

- .changeset/small-ways-live.md
- packages/pharos/src/components/tabs/pharos-tabs.scss
Fixes #473 
Add padding around the tab list to ensure the outline has space to render.
> Tabs: Make selected tab outline fully visible

- .storybook/GuidelineLink.tsx
- packages/pharos/src/components/alert/PharosAlert.react.stories.jsx
- packages/pharos/src/components/toast/PharosToast.react.stories.jsx
Some links got broken when we moved to scoping all Storybook and test elements, and some potentially never worked because they were web component usages in React stories. The worst breakage was that all the "See guidelines in Pharos" links in Storybook's Docs tab were broken.
- Scope the GuidelineLink component
- Update React stories to use React Pharos Links
> Storybook: Update links broken by scoping

- .changeset/stupid-files-jump.md
- .storybook/theme.js
- packages/pharos/src/components/dropdown-menu/pharos-dropdown-menu-item.scss
- packages/pharos/src/components/tabs/pharos-tab-panel.scss
- packages/pharos/src/components/tabs/pharos-tab.scss
- packages/pharos/src/utils/scss/_mixins.scss
Resolves #175 
This change uses `:focus-visible` instead of `:focus` for most interactive elements. Notably, it leaves form controls alone, because the focus styling for those feels quite natural as compared to others.
Where buttons, tabs, and links used to have intrusive boxes placed around them on focus for all users, they will now only display those focus outlines when navigating with keyboards or other input devices. Direct mouse pointer input does not create the outline.
The expectation is that this **increases** accessibility for the set of users using mouse pointers, creating less visual noise and motion, while …
> Use :focus-visible for most interactive elements

- .changeset/unlucky-taxis-press.md
- .svglintrc.js
- packages/pharos/assets/icons/microsoft-color.svg
- packages/pharos/tokens/assets/icons.json
Add Microsoft icon.
Added the icon to the assets and icons.json file.
N/A
> Icon: add microsoft icon

- .changeset/rotten-worms-tell.md
- packages/pharos/src/components/icon/PharosIcon.react.stories.jsx
- packages/pharos/src/components/icon/pharos-icon.wc.stories.jsx
The PharosIcon stories currently have a description argument but it was not actually being passed to the story components, so it is not rendered into the stories. This fixes that.
While working on #467 a group of pharos maintainers discovered that the current icon Storybook stories were broken, and decided to fix them before continuing.
Correctly passes the description arguments to the story components
> Icon: Update stories to correctly pass description to components

- package.json
I added this in #579 hoping it would automatically watch TypeScript files when running Storybook locally, but unfortunately this seems to interfere with certain things like the loading of icons.
You can achieve this yourself by running e.g. `yarn storybook:wc:dev` and `yarn watch:tsc` in separate processes.
> Storybook: remove TypeScript watch from commands

- .changeset/quick-cherries-grab.md
- packages/pharos/src/components/dropdown-menu/pharos-dropdown-menu-item.scss
Adds a fallback color to correct race conditions with different versions of pharos on the page and adhere to [ADR 0008](https://github.com/ithaka/pharos/blob/develop/docs/architecture/decisions/0008-evolve-tokens-in-backward-compatible-manner.md)
Add fallback color if the color variable is not found
> Dropdown Menu: add fallback color for on background variant

- .changeset/fresh-parrots-judge.md
- packages/pharos/src/components/sheet/PharosSheet.react.stories.jsx
- packages/pharos/src/components/sheet/pharos-sheet.scss
- packages/pharos/src/components/sheet/pharos-sheet.test.ts
- packages/pharos/src/components/sheet/pharos-sheet.ts
- packages/pharos/src/components/sheet/pharos-sheet.wc.stories.jsx
Fix the sheet to allow it scroll with long content.
Before:
After:
Add overflow and other css constraints.
Also remove the header and footer from sheet to match what we did for popover.
> Sheet: Add overflow for long content and remove footer

- .changeset/five-moles-add.md
- packages/pharos/src/components/dropdown-menu/pharos-dropdown-menu.scss
- packages/pharos/src/components/footer/pharos-footer.scss
- packages/pharos/src/components/input-group/pharos-input-group.scss
- packages/pharos/src/components/modal/pharos-modal.scss
- packages/pharos/src/components/select/pharos-select.scss
- packages/pharos/src/components/sheet/pharos-sheet.scss
- packages/pharos/src/components/sidenav/pharos-sidenav-menu.scss
- packages/pharos/src/components/sidenav/pharos-sidenav-section.scss
- packages/pharos/src/components/tabs/pharos-tab.scss
Fixes #585 (differently than suggested, removing only the `paint` value but not the `contain` property altogether).
* Change `contain: paint` to `contain: layout` (this needs some scrutiny as this isn't always a safe operation, but where applied here is meant to be so)
* Change `contain: content` to `contain: layout style`
* Change `contain: strict` to `contain: layout size style`
> Remove `paint` value from contain properties

- .changeset/sixty-fishes-cheat.md
- packages/pharos/src/components/sheet/PharosSheet.react.stories.jsx
- packages/pharos/src/components/sheet/pharos-sheet.scss
- packages/pharos/src/components/sheet/pharos-sheet.ts
- packages/pharos/src/components/sheet/pharos-sheet.wc.stories.jsx
We want to allow adding "expended" attribute to expand the sheet from consumer. This feature was broken because the css got overwritten by the height we set with typescript.
Get rid of unused css and use pure typescript to control the height.
> Sheet: allow expansion with attribute

- .changeset/large-tomatoes-pull.md
- packages/pharos/src/components/sidenav/PharosSidenav.react.stories.jsx
- packages/pharos/src/components/sidenav/pharos-sidenav-link.test.ts
- packages/pharos/src/components/sidenav/pharos-sidenav-link.ts
- packages/pharos/src/components/sidenav/pharos-sidenav.wc.stories.jsx
External sidenav links now will open in a new tab matching [the documentation](https://pharos.jstor.org/components/sidenav), as well as having rel="noopener" added to the link.
Closes #538 
If a `PharosSidenavLink` is created with the external option, the link will be rendered with target="_blank" and rel="noopener". If for some reason someone manually specified a target with external it will still respect the target that was set.
- I opted against adding rel="nofollow" as mentioned in the issue because I think there are cases when that wouldn't be the desired value.
- I also updated storybook …
> Update sidenav-links marked as external to open in a new tab

- package.json
The `build-storybook` script was removed in #597 because it seemed unused, but it turns out to have been used by Chromatic for generating build diffs.
Add it back in, referencing the newer, consistently-named `storybook:build` script.
I also sped it up by running all the builds concurrently.
> fix(chromatic): reintroduce build-storybook script

- .changeset/eleven-spoons-shop.md
- packages/pharos/src/components/sidenav/PharosSidenav.react.stories.jsx
When merging the latest develop into this release branch the sidenav component ended up with both the old onBackground and new isOnBackground versions of the attribute in its storybook story. This removes the old version so it is correct.
Removes the deprecated `onBackground` attribute from the storybook story.
> Remove old onBackground attribute from sidenav storybook story

- README.md
The all-contributors badge was stuck at a count of 20, as we seem to have been using a hard-coded image.
This updates the badge to a proper dynamic badge with the right count.
> Fix the all-contributors badge

- .changeset/thirty-carrots-suffer.md
- packages/pharos/src/components/alert/pharos-alert.test.ts
- packages/pharos/src/components/dropdown-menu-nav/pharos-dropdown-menu-nav-category.ts
- packages/pharos/src/components/icon/pharos-icon.test.ts
- packages/pharos/src/components/icon/pharos-icon.ts
- packages/pharos/src/components/text-input/pharos-text-input.test.ts
Fixes #467. 
This is the breaking change followup to #646, removing the icon description and requiring an icon to be correctly annotated for screen readers by providing a title or being marked as hidden.
It does the following for the icon component:
- Removes the deprecated `description` attribute entirely
- No longer defaults to hiding the icon if there is no accessible title provided
- Throws an error if an icon is added without being provided a title or being explicitly marked as hidden
- See [this diagram](https://github.com/ithaka/pharos/pull/646#discussion_r1420728515) for a better …
> Require icon accessibility attributes

- .changeset/flat-clocks-brush.md
- packages/pharos/src/components/combobox/pharos-combobox.scss
Closes #663.
Adds default elevation to the combobox component.
Adds a `box-shadow` set to the `pharos-elevation-level-3` design token to the combobox component
**Screenshots**
Before:
After:
> Combobox: Add default elevation

- .changeset/calm-weeks-own.md
- packages/pharos/src/components/modal/pharos-modal.scss
Closes #665.
Adds default elevation to the modal component.
Adds a `box-shadow` set to the `pharos-elevation-level-5` design token to the modal component
**Screenshot**
> Modal: Add default elevation

- .changeset/quiet-garlics-compete.md
- packages/pharos/src/components/dropdown-menu/pharos-dropdown-menu.scss
Closes #662.
Adds default elevation to the dropdown-menu component.
Adds a `box-shadow` set to the `pharos-elevation-level-3` design token to the dropdown-menu component
**Screenshot**
Before:
After:
> Dropdown Menu: Add default elevation

- .changeset/gold-seas-end.md
- packages/pharos/src/components/icon/pharos-icon.scss
This addresses issue #688 where Pharos icons were not visually appearing while navigating screens with Windows High Contrast Mode.
Added a media query that targets the `forced-colors` user preference and sets the SVG attributes `fill` and `stroke` to the `currentColor`.
Resolves #688 
**References:**
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/forced-colors
https://www.smashingmagazine.com/2022/06/guide-windows-high-contrast-mode/
https://css-tricks.com/accessible-svgs-high-contrast-mode/
https://www.digitalocean.com/community/tutorials/css-currentcolor
> fix(icon): add media query style for WHCM

- .changeset/weak-berries-hunt.md
- packages/pharos/src/components/tabs/pharos-tabs.scss
This change is removing the overflow-y from the panel of the tab component. This change is being made because child nodes of the panel are being confined to that area (see in screenshot). This will allow some flexibility and will let the consumer choose how/if to apply overflow.
Remove overflow-y attribute.
As mentioned above this is a breaking change. Any app/page that is using the tabs component should verify that the UI is working as expected.
> Tabs: Remove overflow-y from pharos-tabs' tab__panels class

- .changeset/tough-buckets-press.md
- packages/pharos/src/components/button/pharos-button.test.ts
- packages/pharos/src/components/button/pharos-button.ts
- packages/pharos/src/components/input-group/pharos-input-group.test.ts
- packages/pharos/src/components/toggle-button-group/PharosToggleButtonGroup.react.stories.jsx
- packages/pharos/src/components/toggle-button-group/pharos-toggle-button-group.wc.stories.jsx
Closes #698 
Because the icon in an icon button is set to aria-hidden="true", it is not visible to screen readers. This change requires an `a11y-label` for icon-only buttons to ensure that the button is accessible.
If a button is created with an `icon` attribute but is not given a `a11y-label` attribute, the component will throw an error.
Note this is only checking the `icon` attribute and not the `icon-right` and `icon-left` attributes, as those are commonly used with additional text, which would also make them accessible.
The test looks a little different as our existing error tests don't …
> Require an accessible label be present for icon-only buttons

- .changeset/strong-hounds-jump.md
- packages/pharos/src/components/table/pharos-table.test.ts
- packages/pharos/src/components/table/pharos-table.ts
Resolves #724 
Adds test to confirm that table that has an empty column header adds an empty table cell.
Updates the `<tb></tb>` to `<td></td>`
> Table: fix the empty table column cell element and add test

- .all-contributorsrc
- .changeset/cold-crews-occur.md
- packages/pharos/package.json
Adds an export for createForumData which is used in other projects.
Closes https://github.com/ithaka/pharos/issues/769
Add export to list in package.json
> Create form data export

- .changeset/weak-scissors-vanish.md
- packages/pharos-site/gatsby-config.js
When updating to Gatsby 5 we inadvertently broke some storybook pages. It will no longer load any content for the stories, returning a 404 with an error like `Refused to display 'https://pharos.jstor.org/' in a frame because it set 'X-Frame-Options' to 'deny'.`
Sets the `Content-Security-Policy` of `pharos.jstor.org` to all content from any jstor page. It appears that in Gatsby 5 Netlify automatically injects it's adapter, which sets the headers to deny. ([thread](https://answers.netlify.com/t/breaking-change-x-frame-options-set-to-deny/102220), [documentation](https://www.netlify.com/blog/gatsby-adapters-realize-the-f …
> Set Content-Security-Policy in Gatsby to allow loading content in Storybook

- .changeset/odd-beds-peel.md
- packages/pharos-site/src/components/Sidenav.tsx
- packages/pharos-site/src/components/layout.module.css
- packages/pharos-site/src/components/layout.tsx
- packages/pharos-site/src/components/variables.module.css
Closes #763
When Pharos v14 was release the default behavior of the sidenav changed
and broke the site navigation. Currently the site does not hide the navigation by default and there is no way to close it:
Adds logic to conditionally show/hide the site side navigation based on screen size. 
The default mobile design could maybe use some love here (No site header, I guessed on the padding etc) We can iterate on that though, at least it will be usable.
https://github.com/user-attachments/assets/285ad533-f6cf-46bf-93c4-0831ff7433af
> Fix pharos-site sidenav on mobile screens

- .changeset/nice-cows-shave.md
- packages/pharos/src/components/table/pharos-table.test.ts
- packages/pharos/src/components/table/pharos-table.ts
If you don't provide a table caption, there is an error thrown with directions how to fix it:
> Table must have an accessible name. Please provide a caption for the table using the `caption` attribute. You can hide the caption visually by setting the `hide-caption-visually` property.
However, the correct property to visually hide it is actually just `hide-caption` not `hide-caption-visually`
Updates the error message to include the correct property in the error message
> Update the table caption warning to recommend correct attribute to visually hide the caption

- .changeset/metal-cougars-taste.md
- packages/pharos/src/components/table/pharos-table.scss
- packages/pharos/src/components/table/pharos-table.ts
- packages/pharos/tokens/components/table.json
Close #806 
Adds new component level tokens for that table and updates the header to have a light gray background by default.
New Default Header:
> Table: Add design tokens and update default header background

- .changeset/fifty-icons-pretend.md
- packages/pharos/src/components/table/PharosTable.react.stories.jsx
- packages/pharos/src/components/table/pharos-table.scss
- packages/pharos/src/components/table/pharos-table.test.ts
- packages/pharos/src/components/table/pharos-table.ts
- packages/pharos/src/components/table/pharos-table.wc.stories.jsx
Closes #805 
Also closes #802 
Adds a `hasStickyHeader` property to the table component which sets `position:sticky` on the `thead` element and keeps it visible when the table is scrolled. 
Once the table is scrolled past the header (so the stickiness will display it over the table) a `table-header--has-active-sticky-header` class will toggle from an IntersectionObserver to set an elevation so it is more visually evident is it displaying over the content. 
❤️  Shoutout to @daneah @elisa-vargas @jialin-he for working together on this at the working session last week!
Because it needed to use …
> Table: Add sticky header option

- .changeset/lovely-shirts-visit.md
- packages/pharos/tokens/components/textarea.json
Update min height styling of text area so that right height is set when rows value is 1
Updating min height styling of text area so that right height is set when rows value is 1
https://ithaka.slack.com/archives/CQGGXAUMA/p1731612431204939
> Textarea: Update min height styling

- .github/dependabot.yml
Resolves #751
We have been manually and sporadically updating dependencies, which is tedious and time consuming. This will reduce effort by presenting sets of package changes that will automatically be checked, which make them easy enough to accept or deny. I've included a few known challenging packages in the `ignore` though I suspect there might be others occasionally. We should prefer to fix the PR up so that the code meets the dependency updates, rather than excluding updates, when possible.
> chore(infra): add dependabot schedule

- packages/pharos/src/components/table-cell/pharos-table-cell.ts
- packages/pharos/src/components/table/pharos-table.wc.stories.jsx
It was impossible to set table cell content to fill the height of a cell. This allow that to happen.
When using slotted content in a table cell, it currently is not possible to set the content to be 100% of the cell. This is because using a slot takes the content our of the normal flow and it doesn't know what height it should use when set to 100%. By adding a resizeObserver to see the height of the cell and set that height manually, the descendant content can set height:100% and it will work as expected.
While each cell will be set to it's own height, the nature of table rows means that all cells in a row will …
> Add a resizeObserver to table cells to set cell height

- .changeset/fresh-bars-talk.md
- packages/pharos/src/components/tabs/PharosTabs.react.stories.jsx
- packages/pharos/src/components/tabs/pharos-tabs.test.ts
- packages/pharos/src/components/tabs/pharos-tabs.ts
- packages/pharos/src/components/tabs/pharos-tabs.wc.stories.jsx
When a tab panel itself contained a set of tabs, clicks on any of the nested tabs would result in the parent set of tabs trying to handle the click in addition to the nested tabs trying to handle the click, resulting in an empty display due to the parent not being able to find the clicked tab in its set of tabs.
When setting up event listeners in `firstUpdated`, ensure that tabs being listened to are in `this`'s set of tabs.
> fix(tabs): ensure that parent tabs don't handle nested child tab clicked accidentally

- packages/pharos/web-test-runner.config.mjs
On Actions runs for tests, WTR will frequently fail to start a browser in the given default 30s. Even though the tests all pass, the overall run fails due to this timeout.
> fix(tests): update browser start timeout to 60s

- .changeset/funny-hotels-fold.md
- packages/pharos-cli/tsconfig.json
- packages/pharos-site/babel.config.js
- packages/pharos-site/tsconfig.json
- packages/pharos/tsconfig.json
See [caniuse](https://caniuse.com/?feats=mdn-javascript_builtins_array_at,mdn-javascript_builtins_regexp_hasindices,mdn-javascript_builtins_object_hasown,mdn-javascript_builtins_error_cause,mdn-javascript_operators_await_top_level,mdn-javascript_classes_private_class_fields,mdn-javascript_classes_private_class_methods,mdn-javascript_classes_static_class_fields,mdn-javascript_classes_static_initialization_blocks)
> chore: update build target to es2022

- lint-staged.config.js
> chore(icon): lint SVG files on pre-commit

- .changeset/public-teeth-hope.md
- packages/pharos-cli/tsconfig.json
- packages/pharos-site/babel.config.js
- packages/pharos-site/tsconfig.json
- packages/pharos/tsconfig.json
In #925 we updated TypeScript to compile to `es2022` instead of `es2021`. While global support suggested this was a safe switch we are finding we are getting more error reports than we had hoped for, specifically users on older safari versions. So we are rolling it back for now, we can revisit it again after some time has passed. 
Reverts the changes to tsconfig to bump the build version
> Revert to targeting es2021 when compiling TypeScript

- .changeset/plenty-memes-unite.md
- packages/pharos-site/initComponents.tsx
- packages/pharos-site/src/components/Sidenav.tsx
- packages/pharos-site/src/pages/components/multiselect-dropdown/index.tsx
- packages/pharos-site/static/guidelines/multiselect-dropdown.docs.tsx
> [!WARNING]  
> This is stacked on top of #962 and should also be merged before a new version of Pharos is released with that component
Stacks on top of #962  to add documentation for the new component
Add a new page to the pharos site with information about the multiselect dropdown and how it should be used
> Add pharos site page for new multiselect dropdown component

- .changeset/plenty-memes-unite.md
- packages/pharos-site/initComponents.tsx
- packages/pharos-site/src/components/Sidenav.tsx
- packages/pharos-site/src/pages/components/multiselect-dropdown/index.tsx
- packages/pharos-site/static/guidelines/multiselect-dropdown.docs.tsx
Adds docs page for multiselect-dropdown
I seem to have somehow rebased away https://github.com/ithaka/pharos/pull/981 while working on #962, this adds it back in so the pharos site page is there.
> Fix adding pharos site page for new multiselect dropdown component

- .changeset/ten-pigs-train.md
- packages/pharos-site/src/pages/design-tokens/global-colors.tsx
Fixes #980 
The `grayscale` `tint` and `feedback` color tokens were not being displayed in the global colors page. The issue was that the array that was being made from the tokens wasn't being flattened properly, making those groups return an empty array.
> Fix the global colors design token page

- .changeset/plenty-grapes-remain.md
- packages/pharos/src/components/multiselect-dropdown/pharos-multiselect-dropdown.ts
There is currently a console.log logging what option was clicked in the click handler of the multiselect-dropdown component
It removes the console.log
It's me, hi, I'm the problem, it's me
> Remove console.log from multiselect-dropdown click handler

- package.json
- yarn.lock
This reverts #1054. It was causing build issues with storybook, It's odd as the chromatic build passed with this change in the original PR which I wouldn't expect, but it's blocking people now so we can revert and revisit. 
Reverts a recent major version package update to @vitejs/plugin-react
> Revert "chore(deps-dev): bump @vitejs/plugin-react from 4.7.0 to 5.0.1 (#1054)"

- .changeset/soft-cobras-live.md
- packages/pharos-site/gatsby-node.js
Revert #1086
Reverts a recent change meant to fix a link in the Pharos docs actually broke it more, making storybook totally unavailable. Reverting for now so I can take a look at it again, but have storybook up in the meantime.
> Revert "docs: fix storybook link from pharos site (#1086)"
