- .changeset/three-items-help.md
- .stylelintignore
- CHANGELOG.md
- README.md
- package.json
- packages/core/package.json
- packages/core/src/components/breadcrumb/pharos-breadcrumb-item.ts
- packages/core/src/components/combobox/pharos-combobox.ts
- packages/core/src/components/dropdown-menu/pharos-dropdown-menu-item.ts
- packages/core/src/components/dropdown-menu/pharos-dropdown-menu.ts
- packages/core/src/components/input-group/pharos-input-group.ts
- packages/core/src/components/link/pharos-link.ts
- packages/core/src/components/modal/pharos-modal.ts
- packages/core/src/components/tabs/pharos-tab.ts
- packages/core/src/components/tooltip/pharos-tooltip.ts
- yarn.lock
Updates `lit-element` and `lit-html` to ease the upgrade to the next major release.
- Update dependencies
- Change `@internalProperty` to `@state`
> chore: update lit for forward-compatible features

- .changeset/silly-chairs-clap.md
- packages/pharos-site/static/guidelines/alert.docs.mdx
- packages/pharos-site/static/guidelines/breadcrumb.docs.mdx
- packages/pharos-site/static/guidelines/button.docs.mdx
- packages/pharos-site/static/guidelines/checkbox.docs.mdx
- packages/pharos-site/static/guidelines/combobox.docs.mdx
- packages/pharos-site/static/guidelines/dropdown-menu-nav.docs.mdx
- packages/pharos-site/static/guidelines/dropdown-menu.docs.mdx
- packages/pharos-site/static/guidelines/footer.docs.mdx
- packages/pharos-site/static/guidelines/header.docs.mdx
- packages/pharos-site/static/guidelines/input-group.docs.mdx
- packages/pharos-site/static/guidelines/link.docs.mdx
- packages/pharos-site/static/guidelines/modal.docs.mdx
- packages/pharos-site/static/guidelines/progress-bar.docs.mdx
- packages/pharos-site/static/guidelines/radio.docs.mdx
- packages/pharos-site/static/guidelines/select.docs.mdx
- packages/pharos-site/static/guidelines/sidenav.docs.mdx
- packages/pharos-site/static/guidelines/template.mdx
- packages/pharos-site/static/guidelines/text-input.docs.mdx
- packages/pharos-site/static/guidelines/textarea.docs.mdx
- packages/pharos-site/static/guidelines/toast.docs.mdx
- packages/pharos-site/static/guidelines/tooltip.docs.mdx
Removes the URLs to storybook stories.
> documentation: remove storybook urls

- .changeset/young-shrimps-decide.md
- packages/pharos/src/components/image-card/PharosImageCard.react.stories.mdx
- packages/pharos/src/components/image-card/pharos-image-card.scss
- packages/pharos/src/components/image-card/pharos-image-card.test.ts
- packages/pharos/src/components/image-card/pharos-image-card.ts
- packages/pharos/src/components/image-card/pharos-image-card.wc.stories.mdx
- packages/pharos/src/components/link/pharos-link.scss
- packages/pharos/src/components/link/pharos-link.ts
Update the Pharos image card collection variant based off design feedback.
- Update collection card styles
- Wrap link around collection image
- Add `no-hover` attribute for links
> feat(pharos): update collection cards

- .changeset/short-shrimps-yawn.md
- README.md
- packages/pharos/docs/1.intro.docs.stories.mdx
Adds a career opportunities section storybook and github repo.
Update markdown files to include section with links to Ithaka and careers page.
> docs: add cta for career opportunities

- .changeset/selfish-apricots-beam.md
- README.md
- packages/pharos-site/src/components/Sidenav.tsx
- packages/pharos-site/src/components/footer.module.css
- packages/pharos-site/src/components/footer.tsx
- packages/pharos-site/src/pages/index.module.css
- packages/pharos-site/src/pages/index.tsx
- packages/pharos/README.md
- packages/pharos/src/components/image-card/PharosImageCard.react.stories.mdx
Add section about careers at ITHAKA to site homepage.
- Add careers section to homepage
- Update Netlify link
> feat: add careers section to homepage

- .storybook/main/manager.js
Add Google Analytics to our main Storybook.
- Add property ID to config
> feat: add GA for main Storybook

- .changeset/yellow-singers-develop.md
- .storybook/main/preview-head.html
- packages/pharos/src/components/checkbox-group/PharosCheckboxGroup.react.stories.mdx
- packages/pharos/src/components/combobox/PharosCombobox.react.stories.mdx
- packages/pharos/src/components/radio-group/PharosRadioGroup.react.stories.mdx
- packages/pharos/src/components/select/PharosSelect.react.stories.mdx
- packages/pharos/src/components/select/pharos-select.wc.stories.mdx
- packages/pharos/src/components/text-input/PharosTextInput.react.stories.mdx
- packages/pharos/src/components/textarea/PharosTextarea.react.stories.mdx
Correct Storybook inconsistencies regarding polyfills and styles.
- Remove polyfills from main Storybook
- Correct styles for React stories
> fix: correct Storybook inconsistencies

- .changeset/friendly-foxes-rescue.md
- packages/pharos/src/components/combobox/PharosCombobox.react.stories.mdx
- packages/pharos/src/components/combobox/pharos-combobox.wc.stories.mdx
- packages/pharos/src/components/select/PharosSelect.react.stories.mdx
fixes #97 
- Update styles usage for React stories
> fix(pharos): update styles usage for React stories

- .changeset/nasty-cows-build.md
- packages/pharos-site/src/components/Sidenav.tsx
- packages/pharos-site/src/components/footer.module.css
- packages/pharos-site/src/components/footer.tsx
- packages/pharos-site/src/pages/brand-expressions/imagery.mdx
- packages/pharos-site/src/pages/brand-expressions/logos.mdx
- packages/pharos-site/src/pages/index.module.css
Update content on the site after reviewing with legal.
- Remove logo downloads
- Update footer copyright statement
- Update imagery copy
- Remove JSTOR terms page
> fix(pharos-site): update content based on legal review

- .all-contributorsrc
- .changeset/selfish-days-hide.md
- README.md
- packages/pharos-site/src/components/statics/DosAndDonts.tsx
https://github.com/ithaka/pharos/issues/115#issue-926633314
Fixes #115 
This change updates the apostrophes used as plurality and missing from contractions with proper grammar. 
> updated proper grammar for dos and don'ts in guideline titles

- .github/workflows/verify.yml
Use the Playwright cli to install browsers [as recommended](https://github.com/microsoft/playwright-github-action#%EF%B8%8F-you-probably-dont-need-github-playwright-action-%EF%B8%8F) by the Github action.
- use Playwright cli to install browsers
> ci: use Playwright cli to install browsers

- .changeset/friendly-knives-teach.md
- packages/pharos-site/src/components/statics/design-token/ColorRow.tsx
- packages/pharos-site/src/components/statics/design-token/TokenTable.tsx
- packages/pharos-site/src/pages/design-tokens/alias-colors.mdx
- packages/pharos-site/src/pages/design-tokens/font-family.mdx
- packages/pharos-site/src/pages/design-tokens/font-size.mdx
- packages/pharos-site/src/pages/design-tokens/font-weight.mdx
- packages/pharos-site/src/pages/design-tokens/global-colors.mdx
- packages/pharos-site/src/pages/design-tokens/line-height.mdx
- packages/pharos-site/src/pages/design-tokens/radius.mdx
- packages/pharos-site/src/pages/design-tokens/spacing.mdx
- packages/pharos-site/src/pages/design-tokens/transitions.mdx
- packages/pharos-site/src/pages/design-tokens/type-scale.mdx
Currently, React throws messages about unique keys and reaching re-render limits. The re-render limits has to do with content being passed in as a prop. If the `content` prop is specified as a dependent, it cause an infinite loop. If it's not, animations don't get updated.
Instead of passing content as a prop, we use the built-in children prop and pass content as children elements.
Unique keys were added to ColorRow to avoid duplicate keys.
> documentation(site): fix react error messages for token pages

- .changeset/selfish-turkeys-vanish.md
- packages/pharos-site/src/pages/contributing/documentation/index.mdx
Update accessibility section on the contributing documentation section of the pharos site.
> docs: update accessibility section

- .changeset/kind-chairs-heal.md
- packages/pharos-site/static/guidelines/image-card.docs.mdx
Update accessibility section for image card component.
> docs(pharos-site): update accessibility section for image card

- .changeset/strange-spiders-watch.md
- packages/pharos-site/src/components/footer.tsx
Allows user to change their cookie settings with link in footer.
> feat(pharos-site): add cookie settings link to footer

- .changeset/rare-icons-agree.md
- packages/pharos/tokens/spacing/base.json
> feat(tokens): add pharos-spacing-10-x token

- .changeset/silly-chicken-attack.md
- packages/pharos/README.md
Resolves #107 
- Update README with instructions
> docs(pharos): instruct to import CSS var tokens

- .changeset/giant-rabbits-occur.md
- package.json
- packages/pharos/package.json
- packages/pharos/src/components/alert/pharos-alert.wc.stories.mdx
- packages/pharos/src/components/button/pharos-button.wc.stories.mdx
- packages/pharos/src/components/combobox/pharos-combobox.wc.stories.mdx
- packages/pharos/src/components/link/pharos-link.wc.stories.mdx
- packages/pharos/src/components/modal/pharos-modal.wc.stories.mdx
- packages/pharos/src/components/text-input/pharos-text-input.wc.stories.mdx
- packages/pharos/src/components/textarea/pharos-textarea.wc.stories.mdx
- packages/pharos/src/components/tooltip/pharos-tooltip.wc.stories.mdx
- yarn.lock
Update Lit and axe-core testing plugin to latest versions.
- Update Lit to latest RC
- Update `@open-wc/testing` and pin `axe-core` to latest version
> chore: update Lit to latest RC

- .changeset/thin-experts-yell.md
- packages/pharos/assets/icons/saved.svg
- packages/pharos/tokens/assets/icons.json
Adds the `saved` icon which is really just an inverse of the existing `save` icon:
> feat(icon): Add saved icon

- .vscode/settings.json
- packages/pharos-site/src/components/footer.tsx
Accessibility navigation using ```<footer>``` landmark on ```footer.tsx```
Wrapped ```footer.tsx``` with ```<footer><footer/>``` landmark tag to make accessibility navigation easier
The suggestion for footer landmark comes from ```axe Devtools```
> fix: wrap footer with landmark for accessibility navigation

- .changeset/mighty-fishes-glow.md
- package.json
- packages/pharos/src/components/modal/pharos-modal.scss
- yarn.lock
Resolves #249 
- Adjust margin to only apply horizontally
Add resolution to fix dependency vulnerability
> fix(modal): adjust footer slotted content spacing

- docs/development/conventions/creating-a-release.md
Adds some docs required for the post release activies
> docs: update release documentation to include post release activties

- .github/ISSUE_TEMPLATE/component_request.md
Requesting a new component is a pretty different (and often more involved) effort than requesting the addition of a feature to an existing component. In particular, more of the design and implementation details are needed to ensure proper consideration.
Separating this template from the feature request template will help differentiate feature requests for existing components from requests for new components, and will ensure we collect sufficient information about the requested component ahead of any further discussion.
> feat: create component request template

- packages/pharos-site/src/components/footer.tsx
[It may not be necessary to include the current year in a copyright statement](https://hynek.me/til/copyright-years/), but the first year of copyright should be included at a minimum. We were only displaying the current year, which is now insufficient as of today.
Update to always include the original year of copyright.
> chore(site): update copyright statement

- .changeset/serious-suns-decide.md
- packages/pharos/src/components/tabs/pharos-tabs.scss
- packages/pharos/src/components/tabs/pharos-tabs.test.ts
- packages/pharos/src/components/tabs/pharos-tabs.ts
- packages/pharos/src/components/tabs/pharos-tabs.wc.stories.mdx
Makes it easier for users to evaluate tabs visually
Adds a boolean property to the tabs component.
> feature: add optional horizontal line to tabs

- .changeset/bright-teachers-doubt.md
- packages/pharos-site/src/components/footer.tsx
- packages/pharos-site/src/pages/index.tsx
- packages/pharos/src/components/header/pharos-header.test.ts
- packages/pharos/src/pages/shared/react/Header.tsx
- packages/pharos/src/pages/shared/wc/header.ts
Fixes #335 
Several paths were defined relative to the current page rather than to the current domain.
Add a leading slash to all relative paths that lacked one.
> fix: update path relativity so all paths resolve correctly

- .changeset/tough-buttons-pull.md
- README.md
- packages/pharos-site/src/components/footer.tsx
- packages/pharos-site/src/pages/index.tsx
- packages/pharos/docs/1.intro.docs.stories.mdx
We want people to be able to get to information about ITHAKA and available career opportunities.
Use the latest appropriate ITHAKA organizational links and use the proper subdomain to save a redirect.
> Fix ITHAKA organizational links

- build-ignore.sh
> fix(build): use proper exit code

- .changeset/stupid-ravens-rest.md
- packages/pharos/src/components/checkbox/pharos-checkbox.ts
- packages/pharos/src/components/radio-button/pharos-radio-button.ts
Reprise of #399 because we missed a release step last go 'round
> Checkbox, RadioButton: allow for scoped pharos links

- .changeset/eleven-pianos-decide.md
- packages/pharos-site/static/guidelines/button.docs.mdx
This change adds information about overlay button variant. Resolves #382.
> Docs: Add documentation for overlay button variant

- .changeset/forty-geckos-repeat.md
- packages/pharos-site/babel.config.js
Fixes #480 
Add source type unambiguous, see https://github.com/babel/babel/issues/12731
> Pharos site: fix pharos site local browser error

- .storybook/main/preview.js
- .storybook/parameters.js
- .storybook/react/preview.js
- .storybook/wc/preview.js
Fixes #476 
Extract parameters into its own module so that remove the side-effect of the other code in shared preview.js.
> Storybook: Fix issue in composed storybook build

- .storybook/main.js
> Storybook: use story store v7

- .storybook/main.js
> Storybook: use babel 7

- .github/workflows/release.yml
`changesets/action@master` is deprecated.
Update to the recommended `@v1` version
> chore(actions): update Atlassian changesets version

- .changeset/grumpy-zoos-worry.md
- packages/pharos-site/src/components/statics/PageSection.tsx
fixes #550
Change `webcomponents` to `web-components` in URLs to reflect changes made when upgrading Storybook
> fix(pharos-site-component-links): update link

- .changeset/cold-comics-love.md
- packages/pharos/src/components/alert/pharos-alert.ts
Fixes #548 
Add `icon-condensed` to the alert close button
> Alert: use icon-condensed for close button

- .changeset/many-papayas-remember.md
- packages/pharos/package.json
> Infra: specify sass as peer dependency for @ithaka/pharos

- docs/architecture/decisions/0009-create-explicit-minimally-exhaustive-accessibility-properties-for-components.md
> Decision: Create explicit, minimally exhaustive accessibility properties for components

- .changeset/rare-foxes-applaud.md
- packages/pharos/src/components/image-card/pharos-image-card.test.ts
- packages/pharos/src/components/image-card/pharos-image-card.ts
Update Image card error variant text
Change the image card image unavailable text from preview not available to Image preview not available
> Image card: update image card error variant text

- .changeset/light-news-compete.md
- packages/pharos/package.json
- yarn.lock
computePosition returns inaccurate values for the x and y coordinates, leading to an incorrect placement of the tooltip.
Updating Floating UI to latest version.
> chore: update Floating UI dependency

- packages/pharos/src/components/sidenav/pharos-sidenav.test.ts
Fixes #574 
Add a timeout to give time for the animation to complete.
> chore(sidenav): fix flaky test

- package.json
- packages/pharos/package.json
- yarn.lock
Bump several dependencies to more recent versions (notably, Storybook) and make some subdependencies resolve to a consistent version.
Closes #604
> Bump dependencies and update resolutions

- .changeset/fresh-wolves-rule.md
- packages/pharos/tokens/color/base.json
> Tokens: improve glacier-blue-40 AAA color contrast

- .all-contributorsrc
- README.md
Adding myself as a contributor
> docs: add @sirrah-tam as a contributor

- .changeset/thick-bugs-sing.md
- packages/pharos/src/components/sheet/pharos-sheet.scss
- packages/pharos/src/components/sheet/pharos-sheet.ts
- 50% as the default height feels short so we expand it to 60% now
- Emit events for expand and collapse so that customers can listen to and make changes accordingly
- change default height
- Emit events
> Sheet: Update default height and emit event for expand and collapse

- .changeset/dull-days-approve.md
- packages/pharos/src/components/loading-spinner/pharos-loading-spinner.scss
- packages/pharos/src/components/loading-spinner/pharos-loading-spinner.test.ts
- packages/pharos/src/components/loading-spinner/pharos-loading-spinner.ts
- packages/pharos/src/components/loading-spinner/pharos-loading-spinner.wc.stories.jsx
- packages/pharos/tokens/components/loading-spinner.json
New variants: small, on-background
Add attributes and update svg
> Loading spinner: add small and on background variant

- .changeset/fast-dodos-swim.md
- package.json
- packages/pharos-cli/package.json
- packages/pharos-site/package.json
- packages/pharos/package.json
- packages/pharos/src/components/alert/pharos-alert.ts
- packages/pharos/src/components/toast/pharos-toast.ts
- packages/pharos/tsconfig.json
- yarn.lock
Resolves #633 
Upgrade TypeScript and supporting packages that have TypeScript as a peer dependency.
> Upgrade to TypeScript 5

- .changeset/eight-dots-cry.md
- packages/pharos-site/static/guidelines/button.docs.mdx
- packages/pharos/src/components/checkbox/PharosCheckbox.react.stories.jsx
- packages/pharos/src/components/checkbox/pharos-checkbox.wc.stories.jsx
- packages/pharos/src/components/dropdown-menu/PharosDropdownMenu.react.stories.jsx
- packages/pharos/src/components/dropdown-menu/pharos-dropdown-menu.wc.stories.jsx
- packages/pharos/src/components/loading-spinner/pharos-loading-spinner.scss
- packages/pharos/src/components/loading-spinner/pharos-loading-spinner.ts
- packages/pharos/src/components/loading-spinner/pharos-loading-spinner.wc.stories.jsx
- packages/pharos/src/components/sidenav/pharos-sidenav.test.ts
- packages/pharos/src/components/sidenav/pharos-sidenav.wc.stories.jsx
- packages/pharos/src/components/toast/pharos-toast.test.ts
We missed a couple of `on-background` -> `is-on-background` changes when making that transition.
> Loading Spinner, Sidenav, Docs: use is-on-background correctly

- netlify.toml
Sets the X-Frame-Options to allow storybook to load iframes
Followup to #778
> Set X-Frame-Options in netlify config

- .changeset/silver-starfishes-look.md
- packages/pharos/src/components/radio-button/pharos-radio-button.ts
#828 
Removes the `aria-label` attribute from the SVG and adds `aria-hidden="true"`
> Radio button: Update SVG to be aria-hidden

- .changeset/silver-suits-wait.md
- packages/pharos/src/components/sidenav/pharos-sidenav.scss
- packages/pharos/src/components/sidenav/pharos-sidenav.ts
before:
after:
Change the icon and position.
> feat(sidenav): update close button

- .changeset/selfish-toys-do.md
- packages/pharos/src/components/sidenav/pharos-sidenav.ts
I just realize I need to use the large icon!!!!
> feat(sidenav): use large icon

- .github/dependabot.yml
> chore(deps): ignore react and react-dom updates

- .github/dependabot.yml
Regarding ithaka/pharos#866
Respond temporarily regarding #866 until we have a fix, so that dependabot updates more often pass and can be merged.
> fix(dependabot): ignore @babel/core updates for the moment

- .github/workflows/verify.yml
Recent test runs in CI are [failing](https://github.com/ithaka/pharos/actions/runs/13364584154/job/37319781961) because playwright isn't properly installed.
> fix(ci): install all dependencies before playwright

- .changeset/spicy-words-love.md
- packages/pharos/src/components/progress-bar/PharosProgressBar.react.stories.jsx
- packages/pharos/src/components/progress-bar/pharos-progress-bar.scss
- packages/pharos/src/components/progress-bar/pharos-progress-bar.test.ts
- packages/pharos/src/components/progress-bar/pharos-progress-bar.ts
- packages/pharos/src/components/progress-bar/pharos-progress-bar.wc.stories.jsx
- packages/pharos/src/components/progress-bar/storyArgs.ts
- yarn.lock
Resolves #878 
Make the `value` property optional, rendering an indeterminate progress bar if unspecified.
> feat(progress-bar): Add  indeterminate progress bar variant

- .changeset/silent-dogs-float.md
- packages/pharos/src/components/sheet/pharos-sheet.ts
> feat(sheet): close sheet on click outside sheet content

- yarn.lock
Fix error from trying to release #1005
> fix(release): upate yarn lock

- .github/CODE_OF_CONDUCT.md
- README.md
Upgrade the code of conduct to the latest version of the Contributor Covenant
> Upgrade code of conduct to Contributor Covenant v2.1

- .changeset/mighty-walls-boil.md
- packages/pharos-site/src/components/statics/color/ColorCombos.tsx
- packages/pharos-site/src/components/statics/color/ColorGradients.tsx
- packages/pharos-site/src/components/statics/color/ColorSwatches.tsx
- packages/pharos-site/src/components/statics/color/ColorTextSquares.tsx
This originally broke from my changes in #1008
> Site: Update color page to use Style Dictionary 5 color token format

- yarn.lock
Adds missing yarn lock file to allow release
Fix broken release in #1022 from missing yarn lock update.
> Update yarn lock to fix release 14.16.1

- packages/pharos/tokens/color/base.json
Added new global colors to Pharos which includes engineering orange and dark garnet.
Resolves #1050
> Add new brand colors
